-- 0033 — Print queue: durable jobs for the in-shop print agent.
--
-- WHY A QUEUE AND NOT A DIRECT CALL
-- The printers live on the shop's private LAN in Glasgow behind a consumer
-- router. apps/api runs on a VPS in Germany and cannot reach them, and a
-- browser cannot open a raw socket or claim a USB device. So a small agent
-- runs inside the shop and PULLS work from here; nothing ever connects
-- inbound to the shop. If the agent is off, the PC asleep, the printer out of
-- paper or the line down, the row simply waits and prints on recovery.
--
-- THE ONE RULE THIS SCHEMA EXISTS TO ENFORCE
-- A receipt must never print twice. Two receipts for one sale is what a
-- fraudulent return looks like, and the customer keeps the paper. Exactly-once
-- delivery is impossible across a network (two generals) — this schema does
-- not pretend otherwise. What it gives instead is AT-MOST-ONCE plus an
-- explicit `unconfirmed` state that asks a human the one question no algorithm
-- can answer: did the paper actually come out?
--
-- Applied to the DEV project only, per the standing hard rule.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type print_job_kind as enum (
  'sale_receipt',
  'refund_receipt',
  'payout_receipt',   -- trade-in money OUT, BUY- series
  'job_label',        -- bench ticket for a repair
  'shelf_label',      -- price/shelf label from the designer
  'test_print'
);

create type print_target as enum ('receipt', 'label');

-- queued     — waiting, nobody holds it
-- leased     — an agent has claimed it and is (or was) working on it
-- printed    — acknowledged by the agent, or confirmed by a human
-- unconfirmed— bytes may have reached the printer; only a person can say
-- failed     — terminal, given up on, visible to staff
create type print_job_status as enum (
  'queued',
  'leased',
  'printed',
  'unconfirmed',
  'failed'
);

create type print_device_status as enum ('ok', 'warning', 'error', 'unknown');

-- ---------------------------------------------------------------------------
-- print_agents — one row per installed agent
-- ---------------------------------------------------------------------------
-- The API has only ever authenticated people (Supabase session cookies, see
-- apps/api/src/lib/session.ts). An agent is a device, not a person, so it gets
-- its own credential — but a deliberately weak one: an agent token may reach
-- ONLY the print endpoints. It can never read products, sales or customers.
-- That matters because this token sits in a config file on a shop PC that
-- anyone behind the counter can touch.
--
-- Only the hash is stored. The token is shown once at issue and is
-- unrecoverable afterwards, the same posture as staff PINs (staff.pin_hash).

create table public.print_agents (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  token_hash    text not null unique,
  -- Exactly one agent may lease work (see the partial unique index below).
  -- A second install is not silently allowed to start splitting the queue
  -- across two printers; it authenticates, heartbeats, and is refused leases
  -- until an owner promotes it.
  is_primary    boolean not null default false,
  last_seen_at  timestamptz,
  agent_version text,
  -- Random per INSTALLATION, generated by the agent on first run. Two
  -- machines running the same copied token share one row but report different
  -- instance ids — which is the only way to detect that case at all.
  last_instance_id text,
  instance_conflict_at timestamptz,
  created_by    uuid references public.staff (id),
  created_at    timestamptz not null default now(),
  revoked_at    timestamptz
);

create unique index print_agents_single_primary_idx
  on public.print_agents (is_primary)
  where is_primary and revoked_at is null;

comment on table public.print_agents is
  'Installed print agents. token_hash only — the token is shown once at issue and never again. At most one non-revoked agent may be primary; only the primary may lease jobs, so a second install cannot silently split the queue across two printers.';

-- ---------------------------------------------------------------------------
-- print_device_health — two rows per agent, one per physical printer
-- ---------------------------------------------------------------------------
-- The shop is in Scotland and the people maintaining this are not. Whether a
-- printer is alive has to be answerable without phoning the shop.
--
-- Deliberately NOT a "down/up" boolean. `unknown` is a real and common answer:
-- see the note on staleness in the API — outside shop_settings.opening_hours a
-- silent agent means the shop is shut, not that anything is broken.

create table public.print_device_health (
  agent_id   uuid not null references public.print_agents (id) on delete cascade,
  target     print_target not null,
  status     print_device_status not null default 'unknown',
  detail     text,
  checked_at timestamptz not null default now(),

  primary key (agent_id, target)
);

comment on table public.print_device_health is
  'Last known state of each physical printer, upserted by the agent on heartbeat. Staleness is judged against shop_settings.opening_hours by the API, so a PC switched off overnight is asleep, not down.';

-- ---------------------------------------------------------------------------
-- print_jobs
-- ---------------------------------------------------------------------------

create table public.print_jobs (
  id      uuid primary key default gen_random_uuid(),
  kind    print_job_kind not null,
  target  print_target not null,

  -- A FROZEN RENDER SNAPSHOT, built by the API at enqueue time.
  --
  -- Two separate decisions are bundled here, both deliberate:
  --
  -- 1. Snapshot, not a reference. This codebase has answered this question
  --    the same way four times already — repair part cost frozen at fitting,
  --    0024's day-close breakdown, 0032's frozen machine label. A reprint
  --    raised during a refund dispute must show what the customer was
  --    actually handed, not what the record says today. It also keeps the
  --    agent's blast radius at one job: an agent that resolves references
  --    needs broad read access, and this one runs unattended on a shop PC.
  --
  -- 2. Built by the SERVER, never posted by the client. The till asks to
  --    print "the receipt for sale X"; the API loads sale X and renders the
  --    snapshot itself. A client that could hand over a finished payload
  --    could print any total it liked onto shop letterhead — which would
  --    walk straight through the standing rule that the server computes
  --    every money figure.
  payload jsonb not null,

  status   print_job_status not null default 'queued',
  attempts integer not null default 0 check (attempts >= 0),
  -- Per row rather than a constant so a test print can be given a different
  -- policy from a customer's receipt without a code change.
  max_attempts integer not null default 3 check (max_attempts >= 1),

  lease_owner      uuid references public.print_agents (id),
  lease_expires_at timestamptz,
  last_error       text,

  -- Attribution comes from the session at enqueue, never from the agent. The
  -- agent is a courier; it has no idea who was at the counter and must never
  -- be asked. Same rule as every money and stock record in this schema.
  requested_by uuid references public.staff (id),

  -- Caller-supplied idempotency key. Pressing "print receipt" twice by
  -- accident is a no-op; a DELIBERATE reprint sends a key with an explicit
  -- reprint suffix, so intent is recorded rather than inferred.
  dedupe_key text not null unique,

  -- Who answered the `unconfirmed` question, and when. A human overruling the
  -- queue is exactly the kind of thing that needs a name against it later.
  resolved_by uuid references public.staff (id),
  resolved_at timestamptz,

  created_at timestamptz not null default now(),
  printed_at timestamptz,

  -- A lease is meaningless without an owner and an expiry, and meaningless
  -- with them in any other state. Kept as a constraint because a half-set
  -- lease is the shape of bug that silently double-prints.
  constraint print_jobs_lease_coherent check (
    (status = 'leased' and lease_owner is not null and lease_expires_at is not null)
    or (status <> 'leased' and lease_owner is null and lease_expires_at is null)
  ),
  constraint print_jobs_printed_at_set check (
    (status = 'printed') = (printed_at is not null)
  )
);

-- The hot path: the agent's long-poll. Partial so the index stays the size of
-- the backlog (usually zero rows) rather than the size of the history.
create index print_jobs_queued_idx
  on public.print_jobs (target, created_at)
  where status = 'queued';

-- The expiry sweep.
create index print_jobs_lease_idx
  on public.print_jobs (lease_expires_at)
  where status = 'leased';

-- The admin screen's "needs a human" list.
create index print_jobs_attention_idx
  on public.print_jobs (created_at desc)
  where status in ('unconfirmed', 'failed');

-- Foreign-key covering indexes.
--
-- Not optional here: test 001 asserts that EVERY foreign key column in this
-- schema has an index whose first key column is that FK column, and these four
-- were the only violations in the database. Without them, deleting a staff row
-- forces a sequential scan of print_jobs to check the references, and the
-- planner has no cheap way to answer "what did this person ask to print".
--
-- Partial where it can be: a lease owner is only meaningful while a job is
-- actually leased, which is almost never more than a handful of rows.
create index print_jobs_lease_owner_idx
  on public.print_jobs (lease_owner)
  where lease_owner is not null;
create index print_jobs_requested_by_idx
  on public.print_jobs (requested_by)
  where requested_by is not null;
create index print_jobs_resolved_by_idx
  on public.print_jobs (resolved_by)
  where resolved_by is not null;
create index print_agents_created_by_idx
  on public.print_agents (created_by)
  where created_by is not null;

comment on table public.print_jobs is
  'Durable print queue. Payload is a server-built frozen snapshot, never client-supplied and never a reference. At-most-once, not exactly-once: a lease that may have reached the printer resolves to unconfirmed and asks a human, because no algorithm can see whether paper came out.';

-- ---------------------------------------------------------------------------
-- Settings — printer configuration and retention
-- ---------------------------------------------------------------------------
-- Follows the shape 0030 used for card_machine_labels: one jsonb column on the
-- singleton settings row, changeable by the owner without a deploy.
--
-- THE THREE ASSUMPTIONS THIS BUILD IS PROCEEDING ON live here, in data, and
-- not in code, which is the entire point — being wrong costs a settings edit:
--
--   1. The POS80GXa is USB-attached and appears as a Windows printer, so we
--      send raw ESC/POS to the Windows print queue. If it turns out to be on
--      the LAN instead, set receipt.transport to "tcp" and fill in host.
--   2. The label roll is 62mm continuous (the DK-2205 starter roll Brother
--      ships with the QL-600). Continuous is self-correcting — we choose the
--      length — so a wrong guess wastes paper rather than cropping a label.
--   3. codepage is UNVERIFIED. cp437 is the ESC/POS default page, but whether
--      THIS clone renders "£" correctly on it is a property of the device, not
--      of the protocol, and only the encoding test print can settle it. The
--      encoder library emits the codepage command; we never write the bytes.
--
-- transport accepts "windows" | "tcp" | "fake". "fake" writes what would have
-- been sent to a file and is a first-class target, not a test hack — it is how
-- the pipeline is exercised with no hardware present and how the real thing
-- gets debugged later.

alter table public.shop_settings
  add column if not exists printer_config jsonb not null default '{
    "receipt": {
      "transport": "windows",
      "windowsPrinterName": null,
      "host": null,
      "port": 9100,
      "paperWidthMm": 80,
      "cut": "partial",
      "codepage": "cp437"
    },
    "label": {
      "transport": "windows",
      "windowsPrinterName": null,
      "rollType": "continuous",
      "rollWidthMm": 62,
      "labelLengthMm": 40
    }
  }'::jsonb;

comment on column public.shop_settings.printer_config is
  'Per-target printer configuration read by the agent. Holds the three researched assumptions (USB/Windows transport for the receipt printer, 62mm continuous label roll, ESC/POS codepage) so that being wrong about any of them is a settings edit, not a code change. codepage is UNVERIFIED until the encoding test print is photographed.';

alter table public.shop_settings
  add column if not exists print_job_retention_days integer not null default 7
    check (print_job_retention_days >= 1);

comment on column public.shop_settings.print_job_retention_days is
  'Days a TERMINAL print job is kept before purge. Short on purpose: payloads carry customer PII (name and phone on a bench-ticket label), and a reprint for a return re-renders from the sale, never from this queue.';

-- ---------------------------------------------------------------------------
-- claim_print_job — the atomic lease
-- ---------------------------------------------------------------------------
-- FOR UPDATE SKIP LOCKED is what makes concurrent claims safe: two callers
-- racing for the same row cannot both win, they take different rows. Written
-- as a function rather than assembled in TypeScript so the atomicity is a
-- property of the database and not of remembering to write it correctly at
-- every call site.
--
-- p_target is nullable so the agent can run one loop per printer. That is not
-- a nicety: a label job that hangs for thirty seconds must not put a customer
-- waiting at the counter behind it.
--
-- Refuses any agent that is not the primary. A second install therefore does
-- nothing rather than quietly halving the queue onto a printer in another room.

create or replace function public.claim_print_job(
  p_agent_id uuid,
  p_lease_seconds integer default 60,
  p_target print_target default null
)
-- SETOF, not a bare composite: a function returning `public.print_jobs`
-- yields a row of all-NULLs when nothing matched, which reads as a job with a
-- null id and is a genuinely easy thing to print by accident. SETOF returns
-- zero rows instead, so "queue empty" is unmistakable at the call site.
returns setof public.print_jobs
language plpgsql
as $$
begin
  if not exists (
    select 1 from public.print_agents
    where id = p_agent_id and is_primary and revoked_at is null
  ) then
    raise exception 'Agent is not the primary print agent.'
      using errcode = 'P0001';
  end if;

  return query
    with claimed as (
      update public.print_jobs j
         set status           = 'leased',
             lease_owner      = p_agent_id,
             lease_expires_at = now() + make_interval(secs => p_lease_seconds),
             attempts         = j.attempts + 1
       where j.id = (
         select id
           from public.print_jobs
          where status = 'queued'
            and (p_target is null or target = p_target)
          order by created_at
          for update skip locked
          limit 1
       )
      returning j.*
    )
    select * from claimed;
end;
$$;

comment on function public.claim_print_job is
  'Atomically leases the oldest queued job (optionally for one target only) to the primary agent. FOR UPDATE SKIP LOCKED guarantees two concurrent callers never take the same row. Raises if the caller is not the primary agent.';

-- ---------------------------------------------------------------------------
-- expire_print_leases — the sweep, and where the receipt/label split lives
-- ---------------------------------------------------------------------------
-- A lease that expires without a word means the agent died, the PC slept, or
-- the line dropped mid-job. We cannot tell which, and critically we cannot
-- tell whether bytes reached the printer.
--
-- So the two targets are treated differently, and this asymmetry is the whole
-- safety argument of the design:
--
--   RECEIPT → unconfirmed. Never requeued automatically. A duplicate receipt
--             in a customer's hand is a dispute; a missing one is a reprint.
--             A person at the counter can look at the paper. Nothing else can.
--
--   LABEL   → requeued while attempts remain. A duplicate label is a wasted
--             inch of roll.
--
-- Returns the number of rows touched so the caller can log it.

create or replace function public.expire_print_leases()
returns integer
language plpgsql
as $$
declare
  v_receipts integer;
  v_labels   integer;
begin
  with expired as (
    update public.print_jobs
       set status           = 'unconfirmed',
           lease_owner      = null,
           lease_expires_at = null,
           last_error       = coalesce(
             last_error,
             'Lease expired with no acknowledgement — may or may not have printed.'
           )
     where status = 'leased'
       and target = 'receipt'
       and lease_expires_at < now()
    returning 1
  )
  select count(*) into v_receipts from expired;

  with expired as (
    update public.print_jobs
       -- The cast is required, not cosmetic. A CASE over two string literals
       -- resolves to `text` before assignment, and Postgres will not coerce
       -- text into an enum column — it fails at runtime, not at create time,
       -- so the function creates cleanly and then throws the first time a
       -- label lease expires. Found by smoke-testing the state machine.
       set status = (case when attempts < max_attempts then 'queued' else 'failed' end)::print_job_status,
           lease_owner      = null,
           lease_expires_at = null,
           last_error       = coalesce(
             last_error,
             'Lease expired with no acknowledgement.'
           )
     where status = 'leased'
       and target = 'label'
       and lease_expires_at < now()
    returning 1
  )
  select count(*) into v_labels from expired;

  return v_receipts + v_labels;
end;
$$;

comment on function public.expire_print_leases is
  'Reclaims leases nobody acknowledged. Receipts become unconfirmed and are NEVER auto-requeued — only a human can see whether paper came out. Labels requeue while attempts remain, because a duplicate label is waste rather than a dispute.';

-- ---------------------------------------------------------------------------
-- print_jobs_due_for_deletion — retention, following 0020 exactly
-- ---------------------------------------------------------------------------
-- SELECT-only, on purpose and for the same reason as
-- documents_due_for_deletion(): the function decides WHAT is safe to remove,
-- the API decides HOW and writes the audit entry. Postgres is not the right
-- place for either half of that.
--
-- Terminal states only. A queued, leased or unconfirmed job is never returned
-- here no matter how old — an unconfirmed job is a question waiting on a
-- person, and silently deleting the question is worse than keeping the row.
-- (That does mean an unresolved unconfirmed job holds its PII indefinitely;
-- the admin screen has to make those impossible to ignore. Flagged, not
-- solved, here.)

create or replace function public.print_jobs_due_for_deletion()
returns table (
  id         uuid,
  kind       print_job_kind,
  target     print_target,
  status     print_job_status,
  created_at timestamptz
)
language sql
stable
as $$
  select j.id, j.kind, j.target, j.status, j.created_at
    from public.print_jobs j
   cross join lateral (
     select print_job_retention_days from public.shop_settings limit 1
   ) s
   where j.status in ('printed', 'failed')
     and j.created_at < now() - make_interval(days => s.print_job_retention_days);
$$;

comment on function public.print_jobs_due_for_deletion is
  'Every print job in a TERMINAL state (printed/failed) past shop_settings.print_job_retention_days. SELECT-only; the API deletes and audits, mirroring documents_due_for_deletion(). Never returns queued/leased/unconfirmed rows regardless of age.';

-- ---------------------------------------------------------------------------
-- Security — RLS, explicitly
-- ---------------------------------------------------------------------------
-- 0011's ALTER DEFAULT PRIVILEGES already handles GRANTs for tables created
-- later, so service_role can read these without another grant. RLS is NOT
-- covered by that mechanism and has to be turned on per table.
--
-- These are the first tables added since 0011. No policies, matching every
-- other table: enabling RLS with zero policies IS the deny-all, and the API
-- reaches them as service_role, which bypasses RLS by a separate mechanism.

alter table public.print_agents        enable row level security;
alter table public.print_agents        force  row level security;
alter table public.print_device_health enable row level security;
alter table public.print_device_health force  row level security;
alter table public.print_jobs          enable row level security;
alter table public.print_jobs          force  row level security;
