/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[];

export type BookingStatus = 'cancelled' | 'dispatched' | 'in_progress' | 'ready' | 'received';

export type CashEntryKind = 'float_open' | 'petty_in' | 'petty_out';

export type DeliveryMethod = 'collect' | 'next_day' | 'standard';

export type DocumentApprovalStatus = 'approved' | 'pending' | 'rejected';

export type DocumentKind = 'buy_in_form' | 'misc';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type JobConversionField =
  | 'accessories_received'
  | 'condition_on_arrival'
  | 'data_backed_up'
  | 'imei'
  | 'passcode'
  | 'quote';

export type JobPaymentStatus = 'deposit_paid' | 'paid' | 'unpaid';

export type JobSource = 'mail_in' | 'online' | 'walk_in';

export type JobStatus =
  'cancelled' | 'collected' | 'done' | 'in_progress' | 'new' | 'sent_back' | 'waiting_approval';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type OrderDocumentKind = 'driving_licence' | 'v5c';

export type OrderStatus = 'cancelled' | 'collected' | 'paid' | 'pending' | 'ready' | 'shipped';

export type PartTier = 'copy' | 'oem' | 'original';

export type Permission =
  | 'analytics.view'
  | 'cash.manage'
  | 'costs.view'
  | 'inventory.manage'
  | 'jobs.manage'
  | 'labels.manage'
  | 'payments.view'
  | 'pos.operate'
  | 'promotions.manage'
  | 'reports.view'
  | 'returns.manage'
  | 'returns.override'
  | 'reviews.manage'
  | 'sales.today'
  | 'settings.manage'
  | 'staff.manage'
  | 'tradein.manage';

export type PrintDeviceStatus = 'error' | 'ok' | 'unknown' | 'warning';

export type PrintJobKind =
  | 'day_report'
  | 'job_label'
  | 'payout_receipt'
  | 'refund_receipt'
  | 'sale_receipt'
  | 'shelf_label'
  | 'test_print';

export type PrintJobStatus = 'failed' | 'leased' | 'printed' | 'queued' | 'unconfirmed';

export type PrintTarget = 'label' | 'receipt';

export type ProductCategory =
  'audio' | 'cases' | 'mounts' | 'plates' | 'power' | 'protection' | 'vape';

export type ProductKind = 'accessory' | 'plate' | 'vape';

export type RepairEnquiryStatus = 'closed' | 'contacted' | 'new';

export type SellRequestStatus =
  'accepted' | 'declined' | 'paid' | 'quoted' | 'received' | 'rejected' | 'submitted';

export type StaffRole = 'employee' | 'owner';

export type StockMovementKind =
  | 'buy_in'
  | 'correction'
  | 'online_order'
  | 'receipt'
  | 'refund_restock'
  | 'repair_part'
  | 'sale'
  | 'write_off';

export type TenderMethod = 'cash' | 'pos1' | 'pos2' | 'transfer';

export interface AuditLog {
  action: string;
  actor_id: string | null;
  /**
   * Name copied at the time of the action, so the trail survives a staff member being removed.
   */
  actor_label: string;
  after: Json | null;
  before: Json | null;
  created_at: Generated<string>;
  entity_id: string | null;
  entity_type: string;
  id: Generated<string>;
  note: string | null;
}

export interface AuthSessions {
  account_id: string;
  created_at: Generated<string>;
  expires_at: string;
  id: Generated<string>;
  last_used_at: Generated<string>;
  revoked_at: string | null;
  token_hash: Buffer;
  user_agent: string | null;
}

export interface AuthTokens {
  account_id: string;
  created_at: Generated<string>;
  expires_at: string;
  id: Generated<string>;
  purpose: string;
  token_hash: Buffer;
  used_at: string | null;
}

export interface Bookings {
  address_line1: string;
  address_line2: string | null;
  city: string | null;
  created_at: Generated<string>;
  customer_id: string | null;
  customer_name: string;
  device_id: string;
  email: string;
  id: Generated<string>;
  notes: string | null;
  phone: string;
  postcode: string;
  preferred_contact: string;
  quoted_price: number | null;
  reference: ColumnType<string, string | undefined, string>;
  repair_type_id: string;
  return_tracking_number: string | null;
  status: Generated<BookingStatus>;
  tier: PartTier | null;
  updated_at: Generated<string>;
}

export interface CashEntries {
  amount: number;
  created_at: Generated<string>;
  id: Generated<string>;
  kind: CashEntryKind;
  note: string;
  staff_id: string;
  trading_day: Generated<string>;
}

export interface Categories {
  created_at: Generated<string>;
  id: Generated<string>;
  /**
   * True for exactly the three mandatory categories (Vape, Number Plates, Mobiles) — see 0064. Protected rows can never be deleted, renamed, re-slugged, or re-parented (categories_protect_mandatory trigger); subcategories under them can still be freely added and removed.
   */
  is_protected: Generated<boolean>;
  label: string;
  parent_id: string | null;
  slug: string;
  updated_at: Generated<string>;
}

export interface CustomerAddresses {
  city: string | null;
  county: string | null;
  created_at: Generated<string>;
  customer_id: string;
  id: Generated<string>;
  is_default: Generated<boolean>;
  label: string | null;
  line1: string;
  line2: string | null;
  postcode: string;
}

export interface Customers {
  created_at: Generated<string>;
  email: string;
  id: string;
  name: string;
  phone: string | null;
  updated_at: Generated<string>;
}

export interface DayClose {
  /**
   * Cash paid out for trade-ins on this trading day, stored positive and subtracted from expected. Money out of the same drawer.
   */
  cash_payouts: number | null;
  cash_refunds: number | null;
  /**
   * Cash taken for repair deposits/balances on this trading day (job_payments, tender=cash), stored positive and ADDED to expected. Money into the same drawer. Repair refunds are not a separate term — they are already inside cash_refunds, which is not filtered by what the refund is linked to.
   */
  cash_repairs: number | null;
  cash_sales: number | null;
  counted_amount: number;
  created_at: Generated<string>;
  expected_amount: number;
  float_open: number | null;
  id: Generated<string>;
  note: string | null;
  petty_in: number | null;
  petty_out: number | null;
  staff_id: string;
  trading_day: Generated<string>;
  variance: ColumnType<number, never, never>;
}

export interface DeliveryPostcodePrefixes {
  prefix: string;
  zone_id: string;
}

export interface DeliveryRates {
  id: Generated<string>;
  method: DeliveryMethod;
  price: number;
  updated_at: Generated<string>;
  zone_id: string;
}

export interface DeliveryZones {
  code: string;
  id: Generated<string>;
  label: string;
}

export interface Devices {
  brand: string;
  created_at: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  price_multiplier: Numeric;
  updated_at: Generated<string>;
}

export interface Documents {
  id: Generated<string>;
  kind: DocumentKind;
  related_entity_id: string | null;
  related_entity_type: string | null;
  reviewed_at: string | null;
  reviewed_by: string | null;
  status: Generated<DocumentApprovalStatus>;
  storage_path: string;
  uploaded_at: Generated<string>;
  uploaded_by: string | null;
}

export interface JobParts {
  added_at: Generated<string>;
  added_by: string | null;
  id: Generated<string>;
  job_id: string;
  product_id: string;
  quantity: Generated<number>;
  stock_movement_id: string;
  unit_cost: number;
}

export interface JobPayments {
  amount: number;
  at: Generated<string>;
  id: Generated<string>;
  job_id: string;
  kind: string;
  staff_id: string | null;
  tender: TenderMethod;
}

export interface Jobs {
  assigned_staff_id: string | null;
  booking_id: string | null;
  cancellation_reason: string | null;
  courier: string | null;
  created_at: Generated<string>;
  customer_name: string;
  deposit_amount: Generated<number>;
  device_description: string;
  device_id: string | null;
  device_returned: boolean | null;
  email: string | null;
  id: Generated<string>;
  /**
   * Change request item 2. The answers to whatever conversion_required_fields asked for, keyed by the same enum values — passcode, condition on arrival, accessories received, and so on. jsonb rather than five columns because the list is admin-configurable; a column per possible question would make changing the list a deploy. Read on one job, never joined or filtered on — the same test 0007 applied to sell_requests.condition.
   */
  intake_details: Generated<Json>;
  notes: string | null;
  order_id: string | null;
  part_tier: PartTier | null;
  payment_status: Generated<JobPaymentStatus>;
  phone: string | null;
  problem_description: string;
  quoted_price: number | null;
  reference: ColumnType<string, string | undefined, string>;
  /**
   * Change request item 6. Which catalogue repair this job is, when it came from the catalogue. Nullable: a free-text job has none. With device_id and part_tier it is what repair_quote_price() needs to recompute the floor server-side, so no floor is ever taken from the request body.
   */
  repair_type_id: string | null;
  return_tracking_number: string | null;
  revised_quote: number | null;
  revised_quote_approved_at: string | null;
  revised_quote_approved_by: string | null;
  source: JobSource;
  status: Generated<JobStatus>;
  updated_at: Generated<string>;
}

export interface LabelTemplates {
  barcode_value: string | null;
  created_at: Generated<string>;
  created_by: string | null;
  id: Generated<string>;
  lines: Json;
  linked_product_id: string | null;
  name: string;
  updated_at: Generated<string>;
}

export interface LowStockProducts {
  category: string | null;
  id: string | null;
  low_stock_threshold: number | null;
  name: string | null;
  stock_qty: number | null;
  variant_id: string | null;
}

export interface OrderDocuments {
  id: Generated<string>;
  kind: OrderDocumentKind;
  order_id: string;
  /**
   * Shown to the customer when asking for originals. Required by the API when status is set to rejected — not enforced here because the review-consistency check already requires reviewed_by/reviewed_at, and a blank reason is a UX bug, not a data-integrity one.
   */
  rejection_reason: string | null;
  reviewed_at: string | null;
  reviewed_by: string | null;
  status: Generated<DocumentApprovalStatus>;
  storage_path: string;
  uploaded_at: Generated<string>;
}

export interface OrderLines {
  cost_price: Generated<number>;
  created_at: Generated<string>;
  id: Generated<string>;
  line_total: ColumnType<number, never, never>;
  name: string;
  order_id: string;
  product_id: string | null;
  quantity: number;
  unit_price: number;
  variant_id: string | null;
}

export interface Orders {
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  county: string | null;
  /**
   * Who the parcel actually went out with (e.g. "Royal Mail", "DPD"). Required by the API the moment status moves to shipped — null before then, and for collect orders always.
   */
  courier: string | null;
  created_at: Generated<string>;
  customer_id: string | null;
  delivery_fee: Generated<number>;
  delivery_method: DeliveryMethod;
  delivery_zone_id: string | null;
  discount: Generated<number>;
  guest_email: string | null;
  id: Generated<string>;
  paid_at: string | null;
  payment_provider: string | null;
  phone: string | null;
  postcode: string | null;
  provider_reference: string | null;
  recipient_name: string | null;
  reference: ColumnType<string, string | undefined, string>;
  status: Generated<OrderStatus>;
  subtotal: number;
  total: ColumnType<number, never, never>;
  /**
   * The courier's own tracking reference. Required alongside courier for the shipped transition — see the note on that column.
   */
  tracking_number: string | null;
  updated_at: Generated<string>;
}

export interface PaymentProviderEvents {
  /**
   * What the PROVIDER reported charging, integer pence. Deliberately separate from orders.total so a mismatch between what we asked for and what was taken is detectable.
   */
  amount: number | null;
  currency: string | null;
  /**
   * The provider's event id. Unique per provider — this is the idempotency key that makes a redelivered webhook a no-op. Enforced by the unique index rather than by a check-then-insert in the handler, which would lose the race against a concurrent retry.
   */
  event_id: string;
  event_type: string;
  failure_code: string | null;
  failure_message: string | null;
  id: Generated<string>;
  /**
   * Nullable on purpose: an event we cannot match to an order must still be recorded. Money that moved with no known order is the most important thing this table can surface.
   */
  order_id: string | null;
  processed_at: string | null;
  provider: string;
  provider_reference: string | null;
  received_at: Generated<string>;
  status: string | null;
}

export interface PrintAgents {
  agent_version: string | null;
  created_at: Generated<string>;
  created_by: string | null;
  id: Generated<string>;
  instance_conflict_at: string | null;
  is_primary: Generated<boolean>;
  last_instance_id: string | null;
  last_seen_at: string | null;
  name: string;
  revoked_at: string | null;
  token_hash: string;
}

export interface PrintDeviceHealth {
  agent_id: string;
  checked_at: Generated<string>;
  detail: string | null;
  status: Generated<PrintDeviceStatus>;
  target: PrintTarget;
}

export interface PrintJobs {
  attempts: Generated<number>;
  created_at: Generated<string>;
  dedupe_key: string;
  id: Generated<string>;
  kind: PrintJobKind;
  last_error: string | null;
  lease_expires_at: string | null;
  lease_owner: string | null;
  max_attempts: Generated<number>;
  payload: Json;
  printed_at: string | null;
  requested_by: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  status: Generated<PrintJobStatus>;
  target: PrintTarget;
}

export interface ProductFolderItems {
  created_at: Generated<string>;
  folder_id: string;
  product_id: string;
  sort_order: Generated<number>;
}

export interface ProductFolders {
  created_at: Generated<string>;
  id: Generated<string>;
  label: string;
  sort_order: Generated<number>;
  updated_at: Generated<string>;
}

export interface ProductImages {
  alt: string | null;
  created_at: Generated<string>;
  id: Generated<string>;
  position: Generated<number>;
  product_id: string;
  url: string;
}

export interface ProductReviews {
  approved_at: string | null;
  approved_by: string | null;
  body: string;
  created_at: Generated<string>;
  customer_id: string;
  id: Generated<string>;
  is_approved: Generated<boolean>;
  product_id: string;
  rating: number;
}

export interface Products {
  barcode: string | null;
  /**
   * Storage object path (not a public URL — buy-in-forms is a private bucket) for the signed buy-in form required when localBuying is true. Set once, on upload; the file itself is never re-processed the way product photos are.
   */
  buy_in_form_path: string | null;
  /**
   * FROZEN as of migration 0045 — a historical snapshot of this product's category at the moment categories became a real table. Not read or written by any code after this migration; category_id is the only source of truth for a product's category going forward. Kept (not dropped) because this project's migrations are additive-only, not because anything still depends on it.
   */
  category: ProductCategory | null;
  /**
   * The product's category — references categories.id. The only source of truth for category, as of 0045 (see products.category's own comment for what that column used to be and why it is frozen, not dropped).
   */
  category_id: string;
  /**
   * Optional device-compatibility note shown as a list on the PDP where relevant, e.g. "iPhone 13-15". Plain text.
   */
  compatibility: string | null;
  /**
   * Weighted average cost. Maintained by the stock trigger, not set directly.
   */
  cost_price: Generated<number>;
  created_at: Generated<string>;
  description: string | null;
  free_delivery: Generated<boolean>;
  /**
   * When true, this product's own price/stock_qty/cost_price/barcode are frozen and unused — every sellable unit is a row in product_variants instead. Never backfilled: existing products default false and are untouched.
   */
  has_variants: Generated<boolean>;
  id: Generated<string>;
  /**
   * Change request item 11. The handset identifier for a phone bought in through the trade-in flow and put on the shelf. NULL for everything that is not a phone, which is almost everything. Deliberately unconstrained in format (a mistyped IMEI recorded is worth more than a correct one refused) and deliberately NOT unique (a handset returned and resold is legitimately a second row). STAFF-ONLY: no public product response selects this column, and that is the enforcement — it is never loaded on a customer-facing path, rather than being loaded and then skipped.
   */
  imei: string | null;
  /**
   * True = sellable at the till (POS) but absent from the customer-facing storefront (GET /products, GET /products/:slug) entirely. Independent of is_active (retired — hidden everywhere) and free for any product EXCEPT Vape (or a Vape subcategory), where products_derive_in_store_only (0078) forces it true and keeps it there — a legal requirement, not a preference. Was independent of kind='vape' as of 0044; that changed in 0078, which is why this comment is being re-set rather than left as 0044 wrote it.
   */
  in_store_only: Generated<boolean>;
  is_active: Generated<boolean>;
  kind: Generated<ProductKind>;
  low_stock_alert: Generated<boolean>;
  low_stock_threshold: Generated<number>;
  name: string;
  price: number;
  slug: string;
  /**
   * Running total, maintained from stock_movements. Never shown to customers.
   */
  stock_qty: Generated<number>;
  sub: string | null;
  supplier_id: string | null;
  /**
   * Optional merchandising badge shown near the product title on the PDP, e.g. "Bestseller". Plain text, not an enum — client-editable copy, not a fixed state.
   */
  tag: string | null;
  updated_at: Generated<string>;
}

export interface ProductVariants {
  barcode: string | null;
  cost_price: Generated<number>;
  created_at: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  low_stock_alert: Generated<boolean>;
  low_stock_threshold: Generated<number>;
  options: Json;
  /**
   * Added to the parent product's price. Effective price = products.price + product_variants.price_adjustment. A zero adjustment needs no special-casing by any reader.
   */
  price_adjustment: Generated<number>;
  product_id: string;
  sku: string;
  stock_qty: Generated<number>;
  updated_at: Generated<string>;
}

export interface PromoTiers {
  id: Generated<string>;
  min_qty: number;
  promotion_id: string;
  unit_price: number;
}

export interface Promotions {
  created_at: Generated<string>;
  created_by: string | null;
  ends_at: string | null;
  /**
   * Which promotion this row belongs to. Rows sharing a group_id are one promotion covering several products. Defaults to its own new group, so a row created directly is a single-product promotion.
   */
  group_id: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  label: string | null;
  product_id: string;
  starts_at: string | null;
  updated_at: Generated<string>;
}

export interface ReferenceRegistry {
  created_at: Generated<string>;
  entity_id: string;
  entity_type: string;
  reference: string;
}

export interface RefundLines {
  created_at: Generated<string>;
  id: Generated<string>;
  name: string;
  product_id: string | null;
  quantity: number;
  refund_id: string;
  restocked: Generated<boolean>;
  unit_price: number;
  variant_id: string | null;
}

export interface Refunds {
  amount: number;
  created_at: Generated<string>;
  id: Generated<string>;
  /**
   * A repair deposit or balance being returned — a cancelled or abandoned job with money already taken. Exactly one of sale_id/order_id/job_id is set (refunds_exactly_one_link); there is no more link-less "goodwill" refund.
   */
  job_id: string | null;
  order_id: string | null;
  original_tender: TenderMethod | null;
  outside_window: Generated<boolean>;
  reason: string;
  /**
   * This refund's own customer-facing reference, REF- series, from issue_reference(). Distinct from the original sale/order reference the refund was taken against — a partial refund needs both to be identifiable on paper.
   */
  reference: ColumnType<string, string | undefined, string>;
  refund_tender: TenderMethod;
  sale_id: string | null;
  staff_id: string;
  /**
   * Stripe's own refund id (re_...), set only for card-tender refunds on an online order — null for every till/cash/goodwill refund, which never touch Stripe. Written once from stripe.refunds.create()'s response, after Stripe has actually confirmed the refund and before create_refund() runs — see pos.routes.ts.
   */
  stripe_refund_id: string | null;
  /**
   * Stripe's refund.status as of the last time this app heard about it — set at creation, kept current by the refund.updated webhook handler for refund methods that settle asynchronously. Null for every non-Stripe refund.
   */
  stripe_refund_status: string | null;
  window_override_by: string | null;
}

export interface RepairEnquiries {
  created_at: Generated<string>;
  customer_name: string;
  device_description: string;
  email: string | null;
  fault_description: string;
  id: Generated<string>;
  phone: string | null;
  status: Generated<RepairEnquiryStatus>;
}

export interface RepairPartTiers {
  id: PartTier;
  name: string;
  sort_order: Generated<number>;
  strap_line: string | null;
  warranty_label: string;
}

export interface RepairTypes {
  base_price_copy: number | null;
  base_price_oem: number | null;
  base_price_original: number | null;
  /**
   * Change request item 2. Which details staff must supply when turning a repair request of this type into a job — the "1-3 missing details" the pop-up asks for. Per repair type because it genuinely varies: a screen replacement needs a passcode to test afterwards, a battery swap on a device that will not power on cannot have one. A closed enum rather than free text so a typo fails loudly instead of silently disabling the prompt.
   */
  conversion_required_fields: Generated<ArrayType<JobConversionField>>;
  created_at: Generated<string>;
  description: string | null;
  estimate_label: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<string>;
}

export interface Reviews {
  body: string;
  created_at: Generated<string>;
  created_by: string | null;
  device: string | null;
  id: Generated<string>;
  name: string;
  published: Generated<boolean>;
  rating: number;
  sort_order: Generated<number>;
  updated_at: Generated<string>;
}

export interface SaleLines {
  cost_price: number;
  /**
   * Change request item 10. True when this is a misc (non-catalogue) line whose cost price was not known at the till, so cost_price is a 0 placeholder rather than a real figure. Distinct from product_id being null, which also happens when a catalogued product is later deleted and whose cost IS known. Cleared by set_sale_line_cost().
   */
  cost_price_pending: Generated<boolean>;
  created_at: Generated<string>;
  id: Generated<string>;
  line_total: ColumnType<number, never, never>;
  list_price: number;
  name: string;
  product_id: string | null;
  quantity: number;
  sale_id: string;
  tier_applied: Generated<boolean>;
  unit_price: number;
  variant_id: string | null;
}

export interface SalePayments {
  amount: number;
  /**
   * Staff member who confirmed this leg, from their session. Null on legs recorded before 0030, and on cash/transfer legs where there is no machine to confirm against.
   */
  confirmed_by: string | null;
  created_at: Generated<string>;
  id: Generated<string>;
  /**
   * The card machine's display name (shop_settings.card_machine_labels), frozen at the moment this leg was confirmed — NOT resolved live. Null for cash/transfer, which have no machine. Frozen so a later provider change (the shop has done this once already) cannot silently relabel historical payments — see 0032.
   */
  machine_label: string | null;
  /**
   * Reference typed off the card machine's receipt slip. Always optional — a missing reference must never block a sale.
   */
  provider_reference: string | null;
  sale_id: string;
  /**
   * How the confirmation arrived: manual (a person read the machine) or auto (a provider API/webhook). An automated confirmation writes the same row with source=auto — it does not get its own table, so the deferred exact-sum trigger still sees every leg.
   */
  source: Generated<string>;
  tender: TenderMethod;
}

export interface Sales {
  below_cost: Generated<boolean>;
  below_cost_reason: string | null;
  cost: Generated<number>;
  created_at: Generated<string>;
  discount: Generated<number>;
  id: Generated<string>;
  reference: ColumnType<string, string | undefined, string>;
  staff_id: string;
  subtotal: number;
  total: ColumnType<number, never, never>;
}

export interface SellRequestAcceptanceTokens {
  created_at: Generated<string>;
  expires_at: string;
  id: Generated<string>;
  sell_request_id: string;
  token_hash: string;
  used_at: string | null;
}

export interface SellRequestPhotos {
  created_at: Generated<string>;
  id: Generated<string>;
  position: Generated<number>;
  sell_request_id: string;
  storage_path: string;
}

export interface SellRequests {
  condition: Json;
  created_at: Generated<string>;
  customer_id: string | null;
  device_id: string | null;
  device_other: string | null;
  email: string;
  id: Generated<string>;
  name: string;
  notes: string | null;
  phone: string;
  preferred_contact: string;
  quoted_amount: number | null;
  quoted_at: string | null;
  quoted_by: string | null;
  reference: ColumnType<string, string | undefined, string>;
  status: Generated<SellRequestStatus>;
  updated_at: Generated<string>;
}

export interface ShopSettings {
  /**
   * Non-working dates on top of weekends. Read by is_working_day(). Seeded with England & Wales 2026-2030; extend it yearly (no settings-screen UI yet — see 0026/0028/0029).
   */
  bank_holidays: Generated<string[]>;
  below_cost_prompts_for_reason: Generated<boolean>;
  /**
   * Display label per card tender, keyed by tender_method value ("pos1"/"pos2"). Reporting metadata resolved at read time; never stored on a payment row. Change this when the shop changes card provider.
   */
  card_machine_labels: Generated<Json>;
  /**
   * Change request item 5. NULL means no limit — every one of the six is independently optional. Counts sale_payments AND job_payments on tender pos1 within the current shop_day(). Enforced by validate_card_payment_limit() and surfaced live by GET /pos/card-limits.
   */
  card1_daily_limit: number | null;
  card1_monthly_limit: number | null;
  card1_weekly_limit: number | null;
  card2_daily_limit: number | null;
  card2_monthly_limit: number | null;
  card2_weekly_limit: number | null;
  customer_email_templates: Generated<Json>;
  float_target: Generated<number>;
  id_document_retention_days: Generated<number>;
  idle_lock_minutes: Generated<number>;
  next_day_cutoff_time: Generated<string>;
  /**
   * Trading hours, one entry per day: {"day","open","close","closed"}. Read by the storefront, the JSON-LD Google indexes, and the print agent health check (which uses it to tell "shop is shut" from "agent is down"). Times are Europe/London wall-clock.
   */
  opening_hours: Generated<Json>;
  /**
   * Days a TERMINAL print job is kept before purge. Short on purpose: payloads carry customer PII (name and phone on a bench-ticket label), and a reprint for a return re-renders from the sale, never from this queue.
   */
  print_job_retention_days: Generated<number>;
  /**
   * How long a LABEL print job may sit queued before it is given up on and marked failed (0090). Default 72h so a job queued on Friday still prints on Monday. Receipts are not covered by this and need no setting — they expire when the shop day turns over. Keep this comfortably below print_job_retention_days: a stale job only becomes purgeable once it is terminal, so a window longer than the retention period would extend how long customer names and phone numbers are held.
   */
  print_job_stale_label_hours: Generated<number>;
  /**
   * Per-target printer configuration read by the agent. Holds the researched hardware assumptions (transport, roll size, ESC/POS code tables) so that being wrong about any of them is a settings edit, not a code change. receipt.transport is CONFIRMED "windows" — the POS80GXa is USB-cabled to the till PC. receipt.codepageCandidates lets the encoder switch code tables mid-line so a pound sign and an accented name can coexist; cp852 support on this clone is UNVERIFIED until the encoding test print is photographed. label.rollWidthMm remains UNVERIFIED — no photograph of the Brother DK roll exists yet.
   */
  printer_config: Generated<Json>;
  receipt_footer_text: string | null;
  receipt_header_text: string | null;
  return_window_days: Generated<number>;
  shop_address: string | null;
  shop_email: string | null;
  shop_name: Generated<string>;
  shop_phone: string | null;
  singleton: Generated<boolean>;
  social_links: Generated<Json>;
  updated_at: Generated<string>;
}

export interface Staff {
  created_at: Generated<string>;
  email: string;
  id: string;
  /**
   * Per-staff auto-lock override, in minutes. Null = use shop_settings.idle_lock_minutes. Only ever set by the staff member themselves — see POST /staff/me/idle-lock.
   */
  idle_lock_minutes: number | null;
  /**
   * Staff are deactivated, never deleted — their name is attached to historical records.
   */
  is_active: Generated<boolean>;
  last_seen_at: string | null;
  name: string;
  phone: string | null;
  pin_hash: string | null;
  role: Generated<StaffRole>;
  updated_at: Generated<string>;
}

export interface StaffFavouriteProducts {
  created_at: Generated<string>;
  product_id: string;
  staff_id: string;
}

export interface StaffPermissions {
  granted_at: Generated<string>;
  granted_by: string | null;
  permission: Permission;
  staff_id: string;
}

export interface StaffSessions {
  device_label: string | null;
  ended_at: string | null;
  id: Generated<string>;
  last_active_at: Generated<string>;
  locked: Generated<boolean>;
  /**
   * Change request item 4. True when this session was obtained by PIN-switching at the till rather than by a full email-and-password sign-in. The API refuses the entire admin surface for such a session, whatever permissions the person holds — the doc requires that Admin always needs a real login, and a restriction enforced only by not drawing a link is not a restriction. Cannot be shed by deleting the cookie: resolveSession treats a staff request with no live staff_sessions row as unauthenticated.
   */
  pos_only: Generated<boolean>;
  staff_id: string;
  started_at: Generated<string>;
}

export interface StockMovements {
  created_at: Generated<string>;
  id: Generated<string>;
  kind: StockMovementKind;
  product_id: string;
  qty_delta: number;
  reason: string | null;
  source_id: string | null;
  source_type: string | null;
  staff_id: string | null;
  unit_cost: number | null;
  /**
   * Null for every movement against a plain (non-variant) product — every historical row is untouched by this column's addition. Set alongside product_id (never instead of it) for a movement against a specific variant.
   */
  variant_id: string | null;
}

export interface Suppliers {
  contact: string | null;
  created_at: Generated<string>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  notes: string | null;
  phone: string | null;
  updated_at: Generated<string>;
}

export interface TodayTakings {
  average_sale: number | null;
  last_sale_at: string | null;
  sales_count: number | null;
  total: number | null;
  trading_day: string | null;
}

export interface TodayTakingsByTender {
  payment_count: number | null;
  tender: TenderMethod | null;
  total: number | null;
}

export interface TradeInPayouts {
  amount: number;
  created_at: Generated<string>;
  customer_name: string;
  device_label: string;
  id: Generated<string>;
  method: string;
  notes: string | null;
  reference: ColumnType<string, string | undefined, string>;
  resale_price: number | null;
  restocked: Generated<boolean>;
  restocked_product_id: string | null;
  sell_request_id: string | null;
  staff_id: string;
}

export interface Transactions {
  amount: number | null;
  at: string | null;
  cost: number | null;
  id: string | null;
  reference: string | null;
  staff_id: string | null;
  stream: string | null;
  tender: string | null;
}

export interface UserAccounts {
  created_at: Generated<string>;
  email: string;
  email_verified_at: string | null;
  /**
   * The stable Google account id (the OIDC `sub` claim) — never the email, which a Google user can change.
   */
  google_sub: string | null;
  id: Generated<string>;
  password_hash: string | null;
  updated_at: Generated<string>;
}

export interface DB {
  audit_log: AuditLog;
  auth_sessions: AuthSessions;
  auth_tokens: AuthTokens;
  bookings: Bookings;
  cash_entries: CashEntries;
  categories: Categories;
  customer_addresses: CustomerAddresses;
  customers: Customers;
  day_close: DayClose;
  delivery_postcode_prefixes: DeliveryPostcodePrefixes;
  delivery_rates: DeliveryRates;
  delivery_zones: DeliveryZones;
  devices: Devices;
  documents: Documents;
  job_parts: JobParts;
  job_payments: JobPayments;
  jobs: Jobs;
  label_templates: LabelTemplates;
  low_stock_products: LowStockProducts;
  order_documents: OrderDocuments;
  order_lines: OrderLines;
  orders: Orders;
  payment_provider_events: PaymentProviderEvents;
  print_agents: PrintAgents;
  print_device_health: PrintDeviceHealth;
  print_jobs: PrintJobs;
  product_folder_items: ProductFolderItems;
  product_folders: ProductFolders;
  product_images: ProductImages;
  product_reviews: ProductReviews;
  product_variants: ProductVariants;
  products: Products;
  promo_tiers: PromoTiers;
  promotions: Promotions;
  reference_registry: ReferenceRegistry;
  refund_lines: RefundLines;
  refunds: Refunds;
  repair_enquiries: RepairEnquiries;
  repair_part_tiers: RepairPartTiers;
  repair_types: RepairTypes;
  reviews: Reviews;
  sale_lines: SaleLines;
  sale_payments: SalePayments;
  sales: Sales;
  sell_request_acceptance_tokens: SellRequestAcceptanceTokens;
  sell_request_photos: SellRequestPhotos;
  sell_requests: SellRequests;
  shop_settings: ShopSettings;
  staff: Staff;
  staff_favourite_products: StaffFavouriteProducts;
  staff_permissions: StaffPermissions;
  staff_sessions: StaffSessions;
  stock_movements: StockMovements;
  suppliers: Suppliers;
  today_takings: TodayTakings;
  today_takings_by_tender: TodayTakingsByTender;
  trade_in_payouts: TradeInPayouts;
  transactions: Transactions;
  user_accounts: UserAccounts;
}
