#!/usr/bin/env node
/**
 * Production DRESS REHEARSAL: docs/go-live.md, run on this machine against the real production
 * images, before there is a server to run it on (deploy/rehearsal/docker-compose.yml says how each
 * Coolify piece is stood in for).
 *
 *   pnpm rehearsal:up      build both images, first deploy (migrations through the entrypoint),
 *                          storage-setup, second deploy WITHOUT the superuser URL, then the
 *                          one-off import of the shop's real set-up (--no-import to skip)
 *   pnpm rehearsal:test    every suite against https://fonology.localtest.me, then the scheduled
 *                          jobs, a backup/restore drill, a graceful stop, and go-live-check last
 *                          (add -- --playwright for the real-browser suite too)
 *   pnpm rehearsal:down    delete all of it, volumes included
 *
 * Secrets are generated into deploy/rehearsal/.env (gitignored). Stripe TEST keys are copied from
 * apps/api/.env.local and apps/web/.env.local when present — never printed, and a live key is
 * never copied. Needs Docker, and ports 80/443/15432/18025 free on 127.0.0.1.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import zlib from 'node:zlib';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'deploy', 'rehearsal');
const envFile = path.join(dir, '.env');
const caFile = path.join(dir, 'caddy-root.crt');
const dumpFile = path.join(dir, 'rehearsal-backup.dump');
const compose = ['compose', '-f', path.join(dir, 'docker-compose.yml')];

const HOSTS = {
  web: 'https://fonology.localtest.me',
  www: 'https://www.fonology.localtest.me',
  api: 'https://api.fonology.localtest.me',
  s3: 'https://s3.fonology.localtest.me',
  storage: 'https://product-images.web.fonology.localtest.me',
};
// The standing test accounts seed-dev creates (TEST-LOGINS.md) — local test data only.
const OWNER = { email: 'owner@fonology.test', password: 'Test1234!' };

function run(cmd, args, { env, capture = false, input, allowFail = false, binary = false } = {}) {
  const r = spawnSync(cmd, args, {
    cwd: root,
    env: { ...process.env, ...env },
    input,
    encoding: binary ? undefined : 'utf8',
    maxBuffer: 1024 * 1024 * 1024,
    stdio: [input === undefined ? 'inherit' : 'pipe', capture ? 'pipe' : 'inherit', 'pipe'],
    shell: process.platform === 'win32' && cmd === 'pnpm',
  });
  if (r.error) throw r.error;
  if (r.status !== 0 && !allowFail) {
    process.stderr.write(binary ? (r.stderr?.toString() ?? '') : (r.stderr ?? ''));
    throw new Error(`${cmd} ${args.join(' ')} exited with ${r.status}`);
  }
  if (!capture && r.stderr?.length) process.stderr.write(r.stderr);
  return { ok: r.status === 0, out: binary ? r.stdout : (r.stdout ?? '').trim() };
}
const dc = (args, opts) => run('docker', [...compose, ...args], opts);
const tsx = (script, env) =>
  run('pnpm', ['--filter', '@fonology/api', 'exec', 'tsx', `scripts/${script}`], { env });

function readEnv(file) {
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return out;
}

/** deploy/rehearsal/.env — generated once, reused until `down`. */
function secrets() {
  if (fs.existsSync(envFile)) return readEnv(envFile);
  const hex = (n) => randomBytes(n).toString('hex');
  const api = readEnv(path.join(root, 'apps/api/.env.local'));
  const web = readEnv(path.join(root, 'apps/web/.env.local'));
  const testOnly = (value, prefix) => (value?.startsWith(prefix) ? value : '');
  const s = {
    POSTGRES_PASSWORD: hex(16),
    FONOLOGY_API_DB_PASSWORD: hex(16),
    GARAGE_RPC_SECRET: hex(32),
    GARAGE_ADMIN_TOKEN: hex(32),
    GARAGE_METRICS_TOKEN: hex(32),
    // The formats Garage accepts for an imported key: GK + 24 hex, and 64 hex.
    S3_ACCESS_KEY_ID: `GK${hex(12)}`,
    S3_SECRET_ACCESS_KEY: hex(32),
    STRIPE_SECRET_KEY: testOnly(api.STRIPE_SECRET_KEY, 'sk_test_'),
    STRIPE_WEBHOOK_SECRET: api.STRIPE_SECRET_KEY?.startsWith('sk_test_')
      ? (api.STRIPE_WEBHOOK_SECRET ?? '')
      : '',
    STRIPE_PUBLISHABLE_KEY: testOnly(web.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY, 'pk_test_'),
  };
  fs.writeFileSync(
    envFile,
    `# Generated by scripts/rehearsal.mjs — local rehearsal only. Deleted by rehearsal:down.\n${Object.entries(
      s,
    )
      .map(([k, v]) => `${k}=${v}`)
      .join('\n')}\n`,
  );
  console.log(
    `[rehearsal] secrets generated; Stripe test keys ${s.STRIPE_SECRET_KEY ? 'copied' : 'NOT found (checkout steps will fail)'}`,
  );
  return s;
}

let failed = 0;
async function step(name, fn) {
  const started = Date.now();
  console.log(`\n\x1b[1m▶ ${name}\x1b[0m`);
  try {
    await fn();
    console.log(`\x1b[32m✓ ${name}\x1b[0m (${Math.round((Date.now() - started) / 1000)} s)`);
  } catch (e) {
    failed += 1;
    console.log(`\x1b[31m✗ ${name}\x1b[0m — ${e.message}`);
    if (!process.argv.includes('--keep-going')) {
      console.log('\nStopped at the first failure (pass --keep-going to carry on).');
      process.exit(1);
    }
  }
}
const assert = (ok, message) => {
  if (!ok) throw new Error(message);
};

async function up() {
  const s = secrets();
  await step('build the production images (apps/api, apps/web Dockerfiles)', () =>
    dc(['build', 'api', 'web']),
  );
  await step('first deploy: the entrypoint applies every migration, then the API starts', () => {
    dc(['up', '-d', '--wait'], {
      env: {
        MIGRATE_DATABASE_URL: `postgres://postgres:${s.POSTGRES_PASSWORD}@postgres:5432/fonology`,
        MIGRATE_API_DB_PASSWORD: s.FONOLOGY_API_DB_PASSWORD,
      },
    });
    const files = fs
      .readdirSync(path.join(root, 'supabase/migrations'))
      .filter((f) => f.endsWith('.sql'));
    const logs = dc(['logs', 'api'], { capture: true }).out;
    const applied = (logs.match(/ applied {2}\S+\.sql/g) ?? []).length;
    const upToDate = /up to date/.test(logs);
    assert(
      applied === files.length || upToDate,
      `${applied} of ${files.length} migrations applied — see docker compose logs api`,
    );
    console.log(
      `  ${upToDate && !applied ? 'already up to date' : `${applied} migrations applied`}`,
    );
  });
  await step('storage-setup (layout, key import, buckets) on a blank Garage', () =>
    dc(['exec', '-T', 'api', 'node', 'dist/scripts/storage-setup.js']),
  );
  await step('second deploy: superuser URL removed, the API still boots', () => {
    dc(['up', '-d', '--wait', 'api'], {
      env: { MIGRATE_DATABASE_URL: '', MIGRATE_API_DB_PASSWORD: '' },
    });
    const leaked = dc(['exec', '-T', 'api', 'printenv', 'MIGRATE_DATABASE_URL'], {
      capture: true,
      allowFail: true,
    }).out;
    assert(!leaked, 'the running API still holds MIGRATE_DATABASE_URL');
    assert(
      !/\[entrypoint\] applying/.test(dc(['logs', 'api'], { capture: true }).out),
      'the second deploy ran migrations',
    );
  });
  // docs/go-live.md §5: the shop's real set-up (categories, staff, settings, delivery, repairs,
  // catalogue) is imported once into the freshly migrated database. The browser suite is written
  // against that data — the migrations' own seed categories are not the shop's. Read-only on the
  // source; skipped (with a warning) when apps/api/.env.local has no DEV_SUPABASE_DB_URL.
  const source = readEnv(path.join(root, 'apps/api/.env.local')).DEV_SUPABASE_DB_URL;
  if (source && !process.argv.includes('--no-import')) {
    await step("import the shop's real set-up (import-from-supabase.js, as on the server)", () =>
      // `-e NAME` with no value: compose passes it from this process's environment, so the URL
      // never appears on a command line.
      dc(
        [
          'exec',
          '-T',
          '-e',
          'DEV_SUPABASE_DB_URL',
          'api',
          'node',
          'dist/scripts/import-from-supabase.js',
        ],
        {
          env: { DEV_SUPABASE_DB_URL: source },
        },
      ),
    );
  } else {
    console.log(
      "\n[rehearsal] no import (no DEV_SUPABASE_DB_URL, or --no-import): the browser suite expects the shop's real categories and will fail in places.",
    );
  }
  await step("copy Caddy's root certificate for the host-side test tools", () =>
    dc(['cp', 'caddy:/data/caddy/pki/authorities/local/root.crt', caFile]),
  );
  console.log(`
Rehearsal is up:
  storefront  ${HOSTS.web}      (the browser will warn about the private CA — expected)
  api         ${HOSTS.api}
  mailpit     http://localhost:18025
  postgres    localhost:15432 (password in deploy/rehearsal/.env)
Next: pnpm rehearsal:test`);
}

/** A solid-colour PNG, built by hand so the rehearsal needs no image library. */
function solidPng(width, height, [r, g, b]) {
  const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(zlib.crc32(Buffer.concat([Buffer.from(type), data])));
    return Buffer.concat([len, Buffer.from(type), data, crc]);
  };
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header.set([8, 2, 0, 0, 0], 8); // 8-bit RGB
  const row = Buffer.concat([Buffer.from([0]), Buffer.from(Array(width).fill([r, g, b]).flat())]);
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', zlib.deflateSync(Buffer.concat(Array(height).fill(row)))),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** One product with a real photo, uploaded through the admin API the way the dialog does it. */
async function photoProduct() {
  const cookies = new Map();
  const call = async (method, url, body) => {
    const res = await fetch(`${HOSTS.api}${url}`, {
      method,
      headers: {
        ...(body instanceof FormData ? {} : { 'content-type': 'application/json' }),
        cookie: [...cookies].map(([k, v]) => `${k}=${v}`).join('; '),
      },
      body: body instanceof FormData ? body : body && JSON.stringify(body),
    });
    for (const line of res.headers.getSetCookie()) {
      const [pair] = line.split(';');
      const eq = pair.indexOf('=');
      cookies.set(pair.slice(0, eq), pair.slice(eq + 1));
    }
    return { status: res.status, body: await res.json().catch(() => null) };
  };
  assert((await call('POST', '/staff/signin', OWNER)).status === 200, 'owner sign-in failed');
  const existing = await call('GET', '/admin/products');
  const rows = Array.isArray(existing.body) ? existing.body : (existing.body?.items ?? []);
  if (rows.some((p) => p.name === 'Rehearsal photo product')) return;
  const png = solidPng(64, 64, [200, 30, 40]);
  const form = new FormData();
  form.append('file', new Blob([png], { type: 'image/png' }), 'rehearsal.png');
  const upload = await call('POST', '/admin/products/images', form);
  assert(upload.status === 201, `photo upload → ${upload.status} ${JSON.stringify(upload.body)}`);
  const cats = await call('GET', '/admin/categories');
  // Any top-level category the database has (a fresh one has the migrations' seed categories).
  const categoryId = cats.body.find((c) => !c.parentId)?.id;
  const created = await call('POST', '/admin/products', {
    name: 'Rehearsal photo product',
    sub: 'Demo catalogue',
    categoryId,
    price: 999,
    costPrice: 300,
    stockQty: 5,
    localBuying: false,
    lowStockAlert: false,
    lowStockThreshold: 3,
    inStoreOnly: false,
    description: 'Made by scripts/rehearsal.mjs.',
    images: [upload.body.url],
  });
  assert(created.status === 201, `product → ${created.status} ${JSON.stringify(created.body)}`);
}

async function test() {
  const s = readEnv(envFile);
  assert(s.POSTGRES_PASSWORD && fs.existsSync(caFile), 'run pnpm rehearsal:up first');
  const env = {
    NODE_EXTRA_CA_CERTS: caFile,
    E2E_API_BASE: HOSTS.api,
    E2E_WEB_BASE: HOSTS.web,
    E2E_MAILPIT_URL: 'http://localhost:18025',
    DATABASE_URL: `postgres://fonology_api:${s.FONOLOGY_API_DB_PASSWORD}@localhost:15432/fonology`,
    STRIPE_WEBHOOK_SECRET: s.STRIPE_WEBHOOK_SECRET,
    ALLOW_TEST_WRITES: 'true',
    AUDIT_STAFF_EMAIL: OWNER.email,
    AUDIT_STAFF_PASSWORD: OWNER.password,
  };
  // Host-side scripts resolve *.localtest.me through public DNS to 127.0.0.1, i.e. Caddy, and
  // trust its CA through NODE_EXTRA_CA_CERTS — read only at process start, hence child processes.

  await step('seed the test accounts (seed-dev)', () => tsx('seed-dev.ts', env));
  await step('seed the demo catalogue through the admin API', () =>
    tsx('seed-demo-catalogue.ts', env),
  );
  await step('upload a product photo through the admin API', () =>
    run(process.execPath, [fileURLToPath(import.meta.url), '_photo'], { env }),
  );
  for (const script of [
    'e2e-test.ts',
    'e2e-variations.ts',
    'e2e-repair-pricing.ts',
    'e2e-shops.ts',
    'schema-audit.ts',
  ]) {
    await step(script, () => tsx(script, env));
  }
  if (process.argv.includes('--playwright')) {
    await step('real-browser suite (packages/e2e)', () =>
      run('pnpm', ['--filter', '@fonology/e2e', 'e2e'], {
        env: { ...env, E2E_IGNORE_HTTPS_ERRORS: '1' },
      }),
    );
  }
  for (const job of [
    'purge-documents',
    'purge-print-jobs',
    'purge-sms-log',
    'purge-housekeeping',
  ]) {
    await step(`scheduled job ${job}`, () =>
      dc(['exec', '-T', 'api', 'node', `dist/scripts/${job}.js`]),
    );
  }
  await step('backup and restore drill (pg_dump -Fc → pg_restore into a scratch database)', () => {
    const psql = (db, sql) =>
      dc(['exec', '-T', 'postgres', 'psql', '-U', 'postgres', '-d', db, '-tAc', sql], {
        capture: true,
      }).out;
    const dump = dc(['exec', '-T', 'postgres', 'pg_dump', '-U', 'postgres', '-Fc', 'fonology'], {
      capture: true,
      binary: true,
    }).out;
    fs.writeFileSync(dumpFile, dump);
    psql('postgres', 'drop database if exists restore_check');
    psql('postgres', 'create database restore_check');
    // stdin goes in with -i semantics (exec -T): `docker exec -it … pg_restore` fails on a pipe.
    dc(['exec', '-T', 'postgres', 'pg_restore', '-U', 'postgres', '-d', 'restore_check'], {
      input: fs.readFileSync(dumpFile),
    });
    for (const table of ['orders', 'sales', 'products', 'user_accounts']) {
      const a = psql('fonology', `select count(*) from ${table}`);
      const b = psql('restore_check', `select count(*) from ${table}`);
      assert(a === b, `${table}: ${a} rows live, ${b} restored`);
      console.log(`  ${table}: ${a} rows, restored ${b}`);
    }
    psql('postgres', 'drop database restore_check');
    fs.rmSync(dumpFile);
  });
  await step('graceful stop: the API exits cleanly on SIGTERM', () => {
    const started = Date.now();
    dc(['stop', '-t', '30', 'api']);
    const seconds = (Date.now() - started) / 1000;
    const id = dc(['ps', '-a', '-q', 'api'], { capture: true }).out;
    const code = run('docker', ['inspect', '-f', '{{.State.ExitCode}}', id], { capture: true }).out;
    assert(code === '0', `exit code ${code}`);
    assert(seconds < 15, `took ${seconds.toFixed(1)} s to stop`);
    console.log(`  stopped in ${seconds.toFixed(1)} s, exit 0`);
  });
  // A fresh API process also clears the in-memory login limiter the suites above may have tripped.
  await step('restart the API', () => dc(['up', '-d', '--wait', 'api']));
  await step('go-live-check against the rehearsal hosts', () =>
    run(process.execPath, [path.join(root, 'scripts/go-live-check.mjs')], {
      env: {
        NODE_EXTRA_CA_CERTS: caFile,
        WEB_URL: HOSTS.web,
        API_URL: HOSTS.api,
        WWW_URL: HOSTS.www,
        STORAGE_URL: HOSTS.storage,
        S3_URL: HOSTS.s3,
        // Caddy's local certificates live 12 hours; Let's Encrypt's are what the 14-day check is for.
        CERT_MIN_DAYS: '0',
      },
    }),
  );
  console.log(failed ? `\n${failed} step(s) failed.` : '\nRehearsal passed.');
  process.exit(failed ? 1 : 0);
}

function down() {
  dc(['down', '-v', '--remove-orphans']);
  for (const f of [envFile, caFile, dumpFile]) fs.rmSync(f, { force: true });
  console.log('[rehearsal] removed');
}

const cmd = process.argv[2];
if (cmd === 'up') await up();
else if (cmd === 'test') await test();
else if (cmd === 'down') down();
else if (cmd === '_photo') await photoProduct();
else {
  console.error('usage: node scripts/rehearsal.mjs up | test [--playwright] [--keep-going] | down');
  process.exit(1);
}
