/**
 * Turns a blank Garage into the one the API expects. Idempotent — safe to run
 * on every deploy, and the ONLY storage step on a new server:
 *
 *   1. layout   a fresh Garage refuses all S3 traffic until its cluster layout
 *               is applied; a single node gets one role, zone dc1.
 *   2. key      S3_ACCESS_KEY_ID / S3_SECRET_ACCESS_KEY are generated by the
 *               operator (see docs/go-live.md §4.2) and IMPORTED here, so the
 *               API's own variables can be set before this runs.
 *   3. buckets  product-images  website access on: anyone can read a photo by its URL
 *               id-documents    private (signed links only)
 *               buy-in-forms    private (signed links only)
 *
 * Buckets are made through Garage's admin API rather than S3 CreateBucket: a
 * bucket made over S3 only gets a name private to the key that made it, and
 * Garage's web endpoint finds buckets by their GLOBAL name. The API's key is
 * then allowed to read and write all three.
 *
 * Photos are served from STORAGE_PUBLIC_URL. The web endpoint picks the bucket
 * from the request's host name, so product-images also gets that host as a
 * global alias (`localhost` locally, `product-images.web.fonology.co.uk` on the
 * server, where garage.toml's root_domain already maps it).
 *
 * GARAGE_ADMIN_URL / GARAGE_ADMIN_TOKEN default to the local stack's when
 * STORAGE_PUBLIC_URL is on localhost.
 *
 *   pnpm storage:setup                    (repo root, local)
 *   node dist/scripts/storage-setup.js    (in the API image)
 */
import { config } from '../config.js';
import { BUCKETS } from '../lib/storage.js';

const publicHost = new URL(config.storagePublicUrl).hostname;
const isLocal = publicHost === 'localhost';
const adminUrl = process.env.GARAGE_ADMIN_URL ?? (isLocal ? 'http://localhost:3903' : undefined);
const adminToken =
  process.env.GARAGE_ADMIN_TOKEN ?? (isLocal ? 'fonology-dev-admin-token' : undefined);

interface BucketInfo {
  id: string;
  globalAliases: string[];
  websiteAccess: boolean;
}

interface ClusterStatus {
  layoutVersion: number;
  nodes: { id: string; dataPartition?: { total: number } }[];
}

async function admin<T>(path: string, body?: unknown): Promise<T | null> {
  const response = await fetch(`${adminUrl}${path}`, {
    method: body === undefined ? 'GET' : 'POST',
    headers: { authorization: `Bearer ${adminToken}`, 'content-type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (response.status === 404) return null;
  if (!response.ok) {
    throw new Error(`Garage admin ${path} → ${response.status} ${await response.text()}`);
  }
  return (await response.json()) as T;
}

/** A single node with no role yet: give it one and apply layout version 1. */
async function ensureLayout() {
  const status = await admin<ClusterStatus>('/v2/GetClusterStatus');
  if (!status) throw new Error('Garage admin: GetClusterStatus not found');
  if (status.layoutVersion > 0) return;
  if (status.nodes.length !== 1) {
    throw new Error(
      `Garage has ${status.nodes.length} nodes and no layout — lay it out by hand, this script only does one node.`,
    );
  }
  const node = status.nodes[0]!;
  // Capacity only weights data between nodes; with one node any figure works. Use the disk's size.
  const capacity = Math.max(node.dataPartition?.total ?? 0, 1_000_000_000);
  await admin('/v2/UpdateClusterLayout', {
    roles: [{ id: node.id, zone: 'dc1', capacity, tags: [] }],
  });
  await admin('/v2/ApplyClusterLayout', { version: 1 });
  console.log('  [storage] single-node layout applied');
}

/** The API's key, as set in its environment. Imported once; never printed. */
async function ensureKey() {
  const existing = await admin(`/v2/GetKeyInfo?id=${encodeURIComponent(config.s3.accessKeyId)}`);
  if (existing) return;
  await admin('/v2/ImportKey', {
    accessKeyId: config.s3.accessKeyId,
    secretAccessKey: config.s3.secretAccessKey,
    name: 'fonology-api',
  });
  console.log(`  [storage] key ${config.s3.accessKeyId} imported`);
}

async function ensureBucket(name: string): Promise<BucketInfo> {
  let info = await admin<BucketInfo>(`/v2/GetBucketInfo?globalAlias=${encodeURIComponent(name)}`);
  if (!info) {
    info = await admin<BucketInfo>('/v2/CreateBucket', { globalAlias: name });
    console.log(`  [storage] ${name}: created`);
  }
  await admin('/v2/AllowBucketKey', {
    bucketId: info!.id,
    accessKeyId: config.s3.accessKeyId,
    permissions: { read: true, write: true, owner: false },
  });
  return info!;
}

async function main() {
  if (!adminUrl || !adminToken) {
    throw new Error('Set GARAGE_ADMIN_URL and GARAGE_ADMIN_TOKEN (the server’s Garage admin API).');
  }

  await ensureLayout();
  await ensureKey();

  for (const name of [BUCKETS.idDocuments, BUCKETS.buyInForms]) {
    const info = await ensureBucket(name);
    // Never public — if one ever was, close it.
    if (info.websiteAccess) {
      await admin(`/v2/UpdateBucket?id=${info.id}`, { websiteAccess: { enabled: false } });
      console.log(`  [storage] ${name}: public reads turned OFF`);
    }
  }

  const images = await ensureBucket(BUCKETS.productImages);
  if (!images.websiteAccess) {
    await admin(`/v2/UpdateBucket?id=${images.id}`, {
      websiteAccess: { enabled: true, indexDocument: 'index.html' },
    });
    console.log(`  [storage] ${BUCKETS.productImages}: public reads on`);
  }
  if (!images.globalAliases.includes(publicHost)) {
    await admin('/v2/AddBucketAlias', { bucketId: images.id, globalAlias: publicHost });
  }
  console.log(`  [storage] photos served at ${config.storagePublicUrl}/<key>`);
}

main().catch((err) => {
  console.error('[storage] setup failed:', err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
